# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_dialog(object):
    def setupUi(self, dialog, run_func=False):
        dialog.setObjectName("dialog")
        dialog.resize(650, 420)
        dialog.setMinimumSize(QtCore.QSize(620, 450))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setItalic(False)
        dialog.setFont(font)
        dialog.setAcceptDrops(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(dialog)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        font.setItalic(False)
        self.tab_1.setFont(font)
        self.tab_1.setAccessibleName("")
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_browser = QtWidgets.QTextBrowser(self.tab_1)
        self.text_browser.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(14)
        font.setItalic(False)
        self.text_browser.setFont(font)
        self.text_browser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_browser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.text_browser.setLineWidth(1)
        self.text_browser.setObjectName("text_browser")
        self.gridLayout_2.addWidget(self.text_browser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        font.setItalic(False)
        self.tab_2.setFont(font)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.spin_box_speed = QtWidgets.QSpinBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.spin_box_speed.setFont(font)
        self.spin_box_speed.setMinimum(1)
        self.spin_box_speed.setMaximum(50)
        self.spin_box_speed.setProperty("value", 10)
        self.spin_box_speed.setObjectName("spin_box_speed")
        self.gridLayout.addWidget(self.spin_box_speed, 3, 3, 1, 1)
        self.label_size = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_size.setFont(font)
        self.label_size.setObjectName("label_size")
        self.gridLayout.addWidget(self.label_size, 0, 0, 1, 2)
        self.combo_box_background_color = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.combo_box_background_color.setFont(font)
        self.combo_box_background_color.setEditable(False)
        self.combo_box_background_color.setObjectName("combo_box_background_color")
        self.combo_box_background_color.addItem("")
        self.combo_box_background_color.addItem("")
        self.gridLayout.addWidget(self.combo_box_background_color, 1, 1, 1, 2)
        self.combo_box_cell_color = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.combo_box_cell_color.setFont(font)
        self.combo_box_cell_color.setObjectName("combo_box_cell_color")
        self.combo_box_cell_color.addItem("")
        self.combo_box_cell_color.addItem("")
        self.combo_box_cell_color.addItem("")
        self.combo_box_cell_color.addItem("")
        self.gridLayout.addWidget(self.combo_box_cell_color, 2, 2, 1, 2)
        self.combo_box_size = QtWidgets.QComboBox(self.tab_2)
        self.combo_box_size.setEnabled(True)
        self.combo_box_size.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.combo_box_size.setFont(font)
        self.combo_box_size.setEditable(False)
        self.combo_box_size.setObjectName("combo_box_size")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.setItemText(2, "100x100")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.gridLayout.addWidget(self.combo_box_size, 0, 3, 1, 1)
        self.label_speed = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_speed.setFont(font)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout.addWidget(self.label_speed, 3, 0, 1, 3)
        self.label_cell_color = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_cell_color.setFont(font)
        self.label_cell_color.setObjectName("label_cell_color")
        self.gridLayout.addWidget(self.label_cell_color, 2, 0, 1, 2)
        self.label_background_color = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_background_color.setFont(font)
        self.label_background_color.setObjectName("label_background_color")
        self.gridLayout.addWidget(self.label_background_color, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.ok_button = QtWidgets.QPushButton(dialog)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.ok_button.setFont(font)
        self.ok_button.setObjectName("ok_button")
        self.verticalLayout.addWidget(self.ok_button)

        self.retranslateUi(dialog)
        self.tabWidget.setCurrentIndex(0)
        self.combo_box_size.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(dialog)

        self.table_size = self.combo_box_size.currentText()
        self.background_color = self.combo_box_background_color.currentText()
        self.cell_color = self.combo_box_cell_color.currentText()
        self.speed = self.spin_box_speed.value()
        self.ok_button_function(run_func, dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Game Of Life"))
        self.text_browser.setHtml(_translate("dialog", rules))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_1), _translate("dialog", "Правила")
        )
        self.label_size.setText(_translate("dialog", "Размер игрового поля:"))
        self.combo_box_background_color.setItemText(0, _translate("dialog", "Black"))
        self.combo_box_background_color.setItemText(1, _translate("dialog", "White"))
        self.combo_box_cell_color.setItemText(0, _translate("dialog", "Green"))
        self.combo_box_cell_color.setItemText(1, _translate("dialog", "Red"))
        self.combo_box_cell_color.setItemText(2, _translate("dialog", "Blue"))
        self.combo_box_cell_color.setItemText(3, _translate("dialog", "Mint"))
        self.combo_box_size.setCurrentText(
            _translate("            print('clicked')dialog", "100x100")
        )
        self.combo_box_size.setItemText(0, _translate("dialog", "50x50"))
        self.combo_box_size.setItemText(1, _translate("dialog", "50x100"))
        self.combo_box_size.setItemText(3, _translate("dialog", "100x150"))
        self.combo_box_size.setItemText(4, _translate("dialog", "200x200"))
        self.label_speed.setText(_translate("dialog", "Скорость (от 1 до 50):"))
        self.label_cell_color.setText(_translate("dialog", "Цвет живой клетки:"))
        self.label_background_color.setText(_translate("dialog", "Цвет фона:"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("dialog", "Опции")
        )
        self.ok_button.setText(_translate("dialog", "OK"))

        self.combo_box_size.currentIndexChanged.connect(self.set_table_size)
        self.combo_box_background_color.currentIndexChanged.connect(
            self.set_background_color
        )
        self.combo_box_cell_color.currentIndexChanged.connect(self.set_cell_color)
        self.spin_box_speed.valueChanged.connect(self.set_speed)

    def ok_button_function(self, run_func, dialog):
        """Закрытие окна меню. Если меню вызывается как модуль,
        то окно завкроется без завершения всей программы.
        """
        if run_func:
            self.ok_button.clicked.connect(dialog.close)
        else:
            self.ok_button.clicked.connect(quit)

    def set_table_size(self):
        self.table_size = self.combo_box_size.currentText()

    def set_background_color(self):
        self.background_color = self.combo_box_background_color.currentText()

    def set_cell_color(self):
        self.cell_color = self.combo_box_cell_color.currentText()

    def set_speed(self):
        self.speed = self.spin_box_speed.value()


# подгрузка правил игры для меню
with open("rules.html", encoding="utf-8") as inp:
    rules = inp.read()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
